name: oneindex
services:
  oneindex:
    public: true
    image: caoyufei/oneindex
    replicas: 1
    environment:
      - MONGO_URI=${MONGO_URI}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - AUTH_USERNAME=${AUTH_USERNAME}
    ports:
      - 8080